#!/usr/bin/php
<?php

// Remote host
$remote = isset($argv[1]) ? $argv[1] : '10.0.0.1';

`ssh rhoban@$remote ./env/stop.sh`;
`ssh rhoban@$remote ./env/boot.sh $remote`;

`echo Booted`;
system("ssh rhoban@$remote ./env/out.sh");
`echo Run out.sh`;
